In [2]:
#question 1
import numpy as np
array1 = np.array([[1,3,4],[3,5,7],[4,8,9]])
list1 = array1.tolist()
print(list1)

[[1, 3, 4], [3, 5, 7], [4, 8, 9]]


In [16]:
#question 2
import numpy as np
print(" choose your array")
a = input()
a = a.split(", ")
a = list(map(int, a))
a = np.array(a)
print("now, choose it's number of line then it's number of column")
a = a.reshape(int(input()),int(input()))
b = a.trace()
print(b)

 choose your array
1, 2, 3, 4, 5, 6, 7, 8, 9
now, choose its number of line then its number of column
3
3
15


In [24]:
#question 3
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("tableau de base: ")
print(x)
print("choisis une valeur inférieur a 40")
a = int(input())
print("valeur supérieur a 10 =", x[x>a])

tableau de base: 
[[ 0 10 20]
 [20 30 40]]
choisis une valeur inférieur a 40
10
valeur supérieur a 10 = [20 20 30 40]


In [18]:
#question 4
import numpy as np
print(" choose your arrays")
a = input()
b = input()
a = a.split(", ")
b = b.split(", ")
a = list(map(int, a))
b = list(map(int, b))
a = np.array(a)
b = np.array(b)
print("now, choose it's number of line then it's number of column")
x = int(input())
y = int(input())
a = a.reshape(x,y)
b = b.reshape(x,y)
C = a+b
print(C)

 choose your arrays
1, 2, 3, 4
4, 3, 2, 1
now, choose it's number of line then it's number of column
2
2
[[5 5]
 [5 5]]


In [22]:
#question 5
import numpy as np
print("Matrice originelle:\n")
X = input()
X = X.split(", ")
X = list(map(int, X))
X = np.array(X)
print("now, choose it's number of line then it's number of column")
X = X.reshape(int(input()),int(input()))
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Matrice originelle:

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
now, choose it's number of line then it's number of column
3
4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Subtract the mean of each row of the said matrix:

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]
